name: html5lib
version: 0.4.4-dev
author: Dart Team <misc@dartlang.org>
description: A library for working with HTML documents.
homepage: https://github.com/dart-lang/html5lib
environment:
  sdk: '>=0.6.5'
dependencies:
  source_maps: '>=0.6.5'
dev_dependencies:
  browser: '>=0.6.5'
  unittest: '>=0.6.5'
