name: html5lib
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/html5lib
description: A library for working with HTML documents.
version: 0.4.3
dependencies:
  source_maps: ">=0.4.5"
dev_dependencies:
  browser: any
  unittest: any
environment:
  sdk: ">=0.4.7"
