name: html5plus
author: "Dart Team <misc@dartlang.org>, Tom Yeh <tomyeh@rikulo.org>"
homepage: https://github.com/tomyeh/html5plus
description: A library for working with HTML and XML documents.
version: 0.0.19
dependencies:
  unittest: { sdk: unittest }
  args: { sdk: args }
  logging: { sdk: logging }
