name: html5plus
authors:
- Dart Team <misc@dartlang.org>
- Tom Yeh <tomyeh@rikulo.org>
homepage: https://github.com/tomyeh/html5plus
description: A fork of html5lib for working with HTML and XML documents.
version: 0.3.2
dependencies:
  browser: '>=0.3.2'
  meta: any
  unittest: any
  source_maps: ">=0.3.0+1 <0.3.1"
environment:
  sdk: ">=0.3.4+0.r18115"
