name: html5plus
version: 0.4.4
authors:
- Dart Team <misc@dartlang.org>
- Tom Yeh <tomyeh@rikulo.org>
description: A fork of html5lib for working with HTML and XML documents.
homepage: https://github.com/tomyeh/html5plus
environment:
  sdk: '>=0.6.5'
dependencies:
  source_maps: '>=0.6.5'
dev_dependencies:
  browser: '>=0.6.5'
  path: '>=0.6.5'
  unittest: '>=0.6.5'
