name: html5plus
author: "Dart Team <misc@dartlang.org>, Tom Yeh <tomyeh@rikulo.org>"
homepage: https://github.com/tomyeh/html5plus
description: A library for working with HTML and XML documents.
version: 0.2.1+1
dependencies:
  meta: any
  unittest: any
